id = "odin"
name = "Odin"
version = "0.3.14"
schema_version = 1
authors = ["Mo Nematzadeh <mohammad.h.nematzadeh@gmail.com>"]
description = "Odin support."
repository = "https://github.com/zed-extensions/odin"

[language_servers.ols]
name = "ols"
language = "Odin"

[grammars.odin]
repository = "https://github.com/tree-sitter-grammars/tree-sitter-odin"
commit = "d2ca8efb4487e156a60d5bd6db2598b872629403"

[debug_locators.odin-main]
